import type { ConfigField, ExerciseConfig } from '../types';

export const configFields: ConfigField[] = [
  {
    key: 'bpm',
    label: 'BPM',
    type: 'number',
    default: 60,
    min: 30,
    max: 300,
    step: 1,
    enabled: true,
    group: 'Tempo',
  },
  {
    key: 'start',
    label: 'Pyramid start',
    type: 'number',
    default: 1,
    min: 1,
    max: 8,
    step: 1,
    enabled: true,
    group: 'Pattern',
    description: 'Lowest subdivision count (kicks per beat)',
  },
  {
    key: 'end',
    label: 'Pyramid end',
    type: 'number',
    default: 4,
    min: 1,
    max: 8,
    step: 1,
    enabled: true,
    group: 'Pattern',
    description: 'Highest subdivision count (kicks per beat). Must be >= Pyramid start.',
  },
  {
    key: 'randomize',
    label: 'Randomize order',
    type: 'action',
    default: false,
    enabled: false,
    group: 'Pattern',
    description: 'Shuffle the subdivision sequence',
  },
  {
    key: 'timerMinutes',
    label: 'Minutes',
    type: 'number',
    default: 15,
    min: 0,
    max: 180,
    step: 1,
    enabled: true,
    group: 'Timer',
  },
  {
    key: 'timerSeconds',
    label: 'Seconds',
    type: 'number',
    default: 0,
    min: 0,
    max: 59,
    step: 1,
    enabled: true,
    group: 'Timer',
  },
];

export const defaultConfig: ExerciseConfig = Object.fromEntries(
  configFields.map((f) => [f.key, f.default]),
);
